# nome da pipeline
name: Run Basic Testes - Scheduler

# em que momento vai ser exutada
on:
  schedule:
    - cron: '0 20,22,23 * * 1-5' 
  

# Jobs -> o que vai ser feito nessa pipeline
# só teremos um job que é o de rodar os testes
jobs: 
  cypress-run:  # nome do meu job
     # em que maq vai rodar os  meus testes
    runs-on: ubuntu-latest   #ubuntu é o linux     

    # steps passo  passo para rodar os testes
    steps:
      # clone do projeto
      - name: Checkout/Clone do projeto 
        uses: actions/checkout@v4

      # exemplo de execução no terminal  
      - name: Instalar dependencias do projeto
        run: npm install

      # execução e confirguração do projeto
      - name: Run testes
        uses: cypress-io/github-action@v6
        with:
          record: True
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}   

      # upload  do relatório mocha
      - name: upload relatório
        uses: actions/upload-artifact@v4 
        with:
          name: Relatório
          path: cypress/reports/html        





